name: Reset Git History

on:
  workflow_dispatch:

jobs:
  reset-history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Reset Git History
        run: |
          set -e
          NEW_BRANCH="latest_branch"
          git fetch origin
          git checkout --orphan "$NEW_BRANCH"
          git add -A
          git commit -m "Reset commit history"
          if git show-ref --verify --quiet refs/heads/main; then
              git branch -D main
          fi
          git branch -m main
          git push -f origin main
          echo "Git history reset successfully."
